{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE OverloadedStrings #-}

-- |
-- Module      : Data.X509.TCG.Compliance.Suggestion
-- License     : BSD-style
-- Maintainer  : Toru Tomita <toru.tomita@gmail.com>
-- Stability   : experimental
-- Portability : unknown
--
-- Auto-fix suggestion types for compliance check results.
--
-- Each compliance check function creates a 'Suggestion' with full context
-- (current values, expected values). This module provides only constructors
-- and formatting helpers.

module Data.X509.TCG.Compliance.Suggestion
  ( Suggestion (..)
  , formatSuggestion
  ) where

import Data.Text (Text)
import Data.Aeson (ToJSON (..), object, (.=))
import GHC.Generics (Generic)

-- | Auto-fix suggestion generated by compliance checks.
-- Each check function creates a Suggestion with full context.
data Suggestion
  = ValueSuggestion
      { sugField    :: !Text
      , sugExpected :: !Text
      }
  | AddField
      { sugField    :: !Text
      , sugExample  :: !(Maybe Text)
      }
  | RemoveField
      { sugField    :: !Text
      , sugReason   :: !Text
      }
  | FixFormat
      { sugField    :: !Text
      , sugFormat   :: !Text
      , sugExample  :: !(Maybe Text)
      }
  | ReferenceInfo
      { sugReference :: !Text
      }
  deriving (Show, Eq, Generic)

-- | Format a suggestion for terminal display.
formatSuggestion :: Suggestion -> Text
formatSuggestion (ValueSuggestion field expected) =
  field <> " " <> expected
formatSuggestion (AddField field mExample) =
  "Add field " <> field <> maybe "" (\ex -> ". Example: " <> ex) mExample
formatSuggestion (RemoveField field reason) =
  "Remove " <> field <> ". " <> reason
formatSuggestion (FixFormat field fmt mExample) =
  field <> " must be " <> fmt <> maybe "" (\ex -> " (e.g., \"" <> ex <> "\")") mExample
formatSuggestion (ReferenceInfo ref) =
  "Reference: " <> ref

instance ToJSON Suggestion where
  toJSON (ValueSuggestion f e) = object
    ["type" .= ("value" :: Text), "field" .= f, "expected" .= e]
  toJSON (AddField f ex) = object
    ["type" .= ("addField" :: Text), "field" .= f, "example" .= ex]
  toJSON (RemoveField f r) = object
    ["type" .= ("removeField" :: Text), "field" .= f, "reason" .= r]
  toJSON (FixFormat f fmt ex) = object
    ["type" .= ("fixFormat" :: Text), "field" .= f, "format" .= fmt, "example" .= ex]
  toJSON (ReferenceInfo r) = object
    ["type" .= ("reference" :: Text), "reference" .= r]
